In [19]:
import pandas as pd

df = pd.read_csv("Motor_Vehicle_Collisions_-_Crashes_20260401.csv")
df.shape

/var/folders/5l/p2bhwq1954j7d9nc9gvmxm000000gn/T/ipykernel_92143/2334237455.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Motor_Vehicle_Collisions_-_Crashes_20260401.csv")

(2252143, 29)

In [20]:
# Parsing: Date & Time
df['CRASH DATE'] = pd.to_datetime(df['CRASH DATE'], errors='coerce')
df['CRASH TIME'] = pd.to_datetime(df['CRASH TIME'], format='%H:%M', errors='coerce')

df[['CRASH DATE', 'CRASH TIME']].head()

  CRASH DATE          CRASH TIME
0 2021-09-11 1900-01-01 02:39:00
1 2022-03-26 1900-01-01 11:45:00
2 2023-11-01 1900-01-01 01:29:00
3 2022-06-29 1900-01-01 06:55:00
4 2022-09-21 1900-01-01 13:21:00

In [ ]:
# Parsing: Number columns
num_cols = [
    'NUMBER OF PERSONS INJURED',
    'NUMBER OF PERSONS KILLED',
    'NUMBER OF PEDESTRIANS INJURED',
    'NUMBER OF PEDESTRIANS KILLED',
    'NUMBER OF CYCLIST INJURED',
    'NUMBER OF CYCLIST KILLED',
    'NUMBER OF MOTORIST INJURED',
    'NUMBER OF MOTORIST KILLED',
    'LATITUDE',
    'LONGITUDE'
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df[num_cols].head()

,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,LATITUDE,LONGITUDE
0,2.0,0.0,0,0,0,0,2,0,NaN,NaN
1,1.0,0.0,0,0,0,0,1,0,NaN,NaN
2,1.0,0.0,0,0,0,0,1,0,40.62179,-73.970024
3,0.0,0.0,0,0,0,0,0,0,NaN,NaN
4,0.0,0.0,0,0,0,0,0,0,NaN,NaN

In [22]:
df.dtypes[['CRASH DATE', 'CRASH TIME'] + num_cols]

CRASH DATE                       datetime64[ns]
CRASH TIME                       datetime64[ns]
NUMBER OF PERSONS INJURED               float64
NUMBER OF PERSONS KILLED                float64
NUMBER OF PEDESTRIANS INJURED             int64
NUMBER OF PEDESTRIANS KILLED              int64
NUMBER OF CYCLIST INJURED                 int64
NUMBER OF CYCLIST KILLED                  int64
NUMBER OF MOTORIST INJURED                int64
NUMBER OF MOTORIST KILLED                 int64
LATITUDE                                float64
LONGITUDE                               float64
dtype: object